MVP_L = GetLocale() == "zhCN" and {
	-- translated by olzenkhaw
	["Set the amount of numbers past the decimal place to show"] = "设置小数点后显示几位数字",
	["Show minimap button"]="显示小地图按钮",
	["Vanquisher"]="胜利者",
	["Protector"]="保卫者",
	["Conqueror"]="征服者",
	["Scale"] = "比例",
	["Enable Sending Enchantment Reminder"] = "开启发送附魔提醒",
	["Average"] = "平均",
	["Enable Showing item level / raid progression on tooltips"]="开启屏幕右下角的信息提示等级 / 团队进度",
	["Enable Showing Raid Progression Details on tooltips"] = "开启屏幕右下角的信息提示具体团队进度",
	["Raid Progression Details"] = "具体大秘境信息",
	["Raid Progression"] = "团队进度",
	["Enable Showing Gear Item Level on Character Frame"] = "开启在角色框体显示装备等级",
	["Item Level"]="等级",
	["Average Item Level"]="平均等级",
	["Export"] = "导出",
	["Not enchanted"] = "无附魔",
	["Not socketed"] = "无宝石",
	["Low level enchanted"] = "低等级附魔",
	["Low level socketed"] = "低等级宝石",
	["Auto Scan"] = "自动扫描",
	["Show overall iLevel at the top of the CharacterFrame"] = "在角色框架顶部显示整体iLevel",
	["Print Loaded Message"] = "打印加载的消息"

} or GetLocale() == "ruRU" and {
	["Set the amount of numbers past the decimal place to show"] = "Определяет количество отображаемых после запятой цифр",
	["Show minimap button"]="Показывать кнопку у миникарты",
	["Vanquisher"]="покорителя",
	["Protector"]="защитника",
	["Conqueror"]="завоевателя",
	-- Translated by petpu
	["Scale"] = "Масштаб",
	["Enable Sending Enchantment Reminder"] = "Включить напоминание о недостающих зачарованиях",
	["Average"] = "Средний",
	["Enable Showing item level / raid progression on tooltips"] = "Отображать уровень предметов и прогресс при наведении на игрока",
	["Enable Showing Raid Progression Details on tooltips"] = "Отображать детальную информацию о прогрессе при наведении на игрока",
	["Raid Progression Details"] = "Детальную информацию о прогрессе",
	["Raid Progression"] = "Прогресс",
	["Enable Showing Gear Item Level on Character Frame"] = "Отображать уровень предметов при наведении на игрока",
	["Item Level"] = "Уровень предметов",
	["Average Item Level"] = "Средний уровень предметов",
	["Export"] = "Экспорт",
	-- Translated by Isceruth
	["Not enchanted"] = "Не зачаровано",
	["Not socketed"] = "Нет самоцвета",
	["Low level enchanted"] = "Низкий уровень зачарования",
	["Low level socketed"] = "Низкий уровень камня",
	["Auto Scan"] = "Авто-сканирование",

} or GetLocale() == "zhTW" and {
	-- ["Set the amount of numbers past the decimal place to show"] = "設置小數點後顯示幾位元數位",
	-- ["Show minimap button"]="顯示小地圖按鈕",
	-- ["Vanquisher"]="勝利者",
	-- ["Protector"]="保衛者",
	-- ["Conqueror"]="征服者",
	-- -- translated by olzenkhaw
	-- ["Scale"] = "比例",
	-- ["Enable Sending Enchantment Reminder"] = "開啟發送附魔提醒",
	-- ["Average"] = "平均",
	-- ["Enable Showing item level / raid progression on tooltips"]="開啟屏幕右下角的信息提示等級/ 團隊​​進度",
	-- ["Enable Showing Raid Progression Details on tooltips"] = "開啟屏幕右下角的信息提示具體團隊進度",
	-- ["Raid Progression Details"] = "具體團隊進度",
	-- ["Raid Progression"] = "團隊進度",
	-- ["Enable Showing Gear Item Level on Character Frame"] = "開啟在角色框架顯示裝備等級",
	-- ["Item Level"]="等級",
	-- ["Average Item Level"]="平均等级",
	-- ["Export"] = "導出",
	-- ["Not enchanted"] = "無附魔",
	-- ["Not socketed"] = "無寶石",
	-- ["Low level enchanted"] = "低等級附魔",
	-- ["Low level socketed"] = "低等級寶石",
	-- ["Auto Scan"] = "自動掃描",
	 ["Set the amount of numbers past the decimal place to show"] = "設置小數點後顯示幾位元數位",
	 ["Show minimap button"]="顯示小地圖按鈕",
	 ["Vanquisher"]="勝利者",
	 ["Protector"]="保衛者",
	 ["Conqueror"]="征服者",
	 -- translated by olzenkhaw
	 ["Scale"] = "比例",
	 ["Enable Sending Enchantment Reminder"] = "開啟發送附魔提醒",
	 ["Average"] = "平均",
	 ["Enable Showing item level / raid progression on tooltips"]="開啟屏幕右下角的信息提示等級/ 團隊進度",
	 ["Enable Showing Raid Progression Details on tooltips"] = "開啟屏幕右下角的信息提示具體團隊進度",
	 ["Raid Progression Details"] = "具體團隊進度",
	 ["Raid Progression"] = "團隊進度",
	 ["Enable Showing Gear Item Level on Character Frame"] = "開啟在角色框架顯示裝備等級",
	 ["Item Level"]="等級",
	 ["Average Item Level"]="平均等級",
	 ["Export"] = "導出",
	 ["Not enchanted"] = "無附魔",
	 ["Not socketed"] = "無寶石",
	 ["Low level enchanted"] = "低等級附魔",
	 ["Low level socketed"] = "低等級寶石",
	 ["Auto Scan"] = "自動掃瞄",

} or GetLocale() == "koKR" and {
	["Set the amount of numbers past the decimal place to show"] = "좌표 표시의 소수점 자릿수를 선택합니다",
	["Show minimap button"]="미니맵 버튼 표시",
	["Vanquisher"]="제압자",
	["Protector"]="수호자",
	["Conqueror"]="정복자",
	-- Translated by kisswow and yuk6196
	["Scale"] = "크기",
	["Enable Sending Enchantment Reminder"] = "누락 마법부여 알림 보내기 활성",
	["Average"] = "평균",
	["Enable Showing item level / raid progression on tooltips"] = "툴팁에 아이템레벨 / 레이드 진행 표시 활성화",
	["Enable Showing Raid Progression Details on tooltips"] = "툴팁에 레이드 진행 상황 활성화",
	["Raid Progression Details"] = "레이드 진행 상황",
	["Raid Progression"] = "레이드 진행",
	["Enable Showing Gear Item Level on Character Frame"] = "캐릭터 창에 장비 아이템 레벨 표시 활성화",
	["Item Level"] = "아이템 레벨",
	["Average Item Level"] = "평균 아이템 레벨",
	["Export"] = "내보내기",
	-- traslated by yuk6196
	["Not enchanted"] = "마법부여 안됨",
	["Not socketed"] = "보석장착 안됨",
	["Low level enchanted"] = "낮은 등급 마법부여",
	["Low level socketed"] = "낮은 등급 보석 장착",
	["Auto Scan"] = "시 자동 스캔",

} or GetLocale() == "frFR" and {
	["Set the amount of numbers past the decimal place to show"] = "Définit le nombre de chiffres à afficher après la virgule",
	["Show minimap button"]="Bouton de la minicarte",
	["Vanquisher"]="vainqueur",
	["Protector"]="protecteur",
	["Conqueror"]="conquérant",
	-- Translated by Protosama
	["Enable Showing item level / raid progression on tooltips"] = "Voir le Niveau d'objet / Progression en raid dans l'infobulle",
	["Enable Showing Raid Progression Details on tooltips"] = "Voir les détails de la Progression en raid dans l'infobulle",
	["Enable Sending Enchantment Reminder"] = "Activer le rappel d'envoi des enchantements",
	["Raid Progression Details"] = "Détails de la Progression en raid",
	["Raid Progression"] = "Progression en raid",
	["Enable Showing Gear Item Level on Character Frame"] = "Voir le Niveau d'objet dans la fiche du personnage",
	["Average"] = "Moyen",
	["Scale"] = "Echelle",
	["Average Item Level"] = "Niveau d'objet moyen",
	["Item Level"] = "Niveau d'objet",
	["Export"] = "Exporter",
	-- Translated by loahn
	["Not enchanted"] = "Non enchanté",
	["Not socketed"] = "Non gemmé",
	["Low level enchanted"] = "Enchantement de bas niveau",
	["Low level socketed"] = "Gemme de bas niveau",
	["Auto Scan"] = "Scan automatique",

} or GetLocale() == "deDE" and {
	["Set the amount of numbers past the decimal place to show"] = "Festlegen der Anzahl der Nachkommastellen",
	["Show minimap button"]="Zeige Minimap-Button",
	["Vanquisher"]="bezwingers",
	["Protector"]="beschützers",
	["Conqueror"]="roberers",
	-- Translated by FireEmerald
	["Enable Showing item level / raid progression on tooltips"] = "Item Level / Raidfortschritt im Tooltip anzeigen",
	["Enable Showing Raid Progression Details on tooltips"] = "Detaillierte Informationen zum Raidfortschritt im Tooltip anzeigen",
	["Raid Progression Details"] = "Detaillierte Informationen zum Raidfortschritt",
	["Raid Progression"] = "Raidfortschritt",
	["Enable Sending Enchantment Reminder"] = "Andere Spieler über fehlende Verzauberungen informieren",
	["Enable Showing Gear Item Level on Character Frame"] = "Item Level der Ausrüstung im Charakterbildschirm anzeigen",
	["Average"] = "Durchschnitt",
	["Scale"] = "Fenstergröße",
	["Average Item Level"] = "Durchschnittliches Item Level",
	["Item Level"] = "Item Level",
	["Export"] = "Export",
	["Low level enchanted"] = "Niedrigstufig verzaubert",
	["Low level socketed"] = "Niedrigstufig gesockelt",
	["Not enchanted"] = "Nicht verzaubert",
	["Not socketed"] = "Nicht gesockelt",
	["Auto Scan"] = "Automatisches Scannen",

} or GetLocale() == "ptBR" and {
	["Set the amount of numbers past the decimal place to show"] = "Escolha o quanto de números além dos decimais serão mostrados",
	["Show minimap button"]="Mostrar botão no mini-mapa",
	["Vanquisher"]="Subjugador",
	["Protector"]="Protetor",
	["Conqueror"]="Conquistador",
	-- Translated by Bombtrap
	["Enable Showing item level / raid progression on tooltips"] = "Ativar mostrar item level / progressão de raide no painel",
	["Enable Showing Raid Progression Details on tooltips"] = "Ativar mostrar detalhes da progressão de raide no painel",
	["Raid Progression Details"] = "Detalhes da progressão de raide",
	["Raid Progression"] = "Progressão de raide",
	["Enable Sending Enchantment Reminder"] = "Ativar envio de lembrete de encante",
	["Enable Showing Gear Item Level on Character Frame"] = "Ativar mostrar item level no painel de personagem",
	["Average"] = "Média",
	["Scale"] = "Escala",
	["Average Item Level"] = "Média de Item Level",
	["Item Level"] = "Item Level",
	["Export"] = "Exportar",
	-- Translated by Gaxn
	["Not enchanted"] = "Não encantado",
	["Not socketed"] = "Não engastado",
	["Low level enchanted"] = "Encantamento de level baixo",
	["Low level socketed"] = "Engaste de level baixo",
	["Auto Scan"] = "Auto Scan",

} or GetLocale() == "esMX" and {
	["Set the amount of numbers past the decimal place to show"] = "Establecer la cantidad de números más allá de la posición decimal para mostrar",
	["Show minimap button"]="Mostrar botón minimapa",
	["Vanquisher"]="vencedor",
	["Protector"]="protector",
	["Conqueror"]="conquistador",
	-- Translated by BakuraExel
	["Enable Showing item level / raid progression on tooltips"] = "Mostrar el nivel de objeto / Progreso en banda en la descripción emergente/tooltip",
	["Enable Showing Raid Progression Details on tooltips"] = "Mostrar progreso en banda detallado en la descripción emergente/tooltip",
	["Raid Progression Details"] = "Progreso en banda detallado",
	["Raid Progression"] = "Progreso en banda",
	["Enable Sending Enchantment Reminder"] = "Enviar recordatorio de encantamiento",
	["Enable Showing Gear Item Level on Character Frame"] = "Mostrar nivel de objeto promedio en el cuadro del personaje",
	["Average"] = "Promedio",
	["Scale"] = "Ampliar",
	["Average Item Level"] = "Nivel de objeto promedio",
	["Item Level"] = "Nivel de objeto",
	["Export"] = "Exportar",
	["Not enchanted"] = "No encantado",
	["Not socketed"] = "Sin gema",
	["Low level enchanted"] = "Encanto menor",
	["Low level socketed"] = "Gema menor",
	["Auto Scan"] = "Auto escáner",

} or GetLocale() == "esES" and {
	["Set the amount of numbers past the decimal place to show"] = "Establecer la cantidad de números más allá de la posición decimal para mostrar",
	["Show minimap button"]="Mostrar botón minimapa",
	["Vanquisher"]="vencedor",
	["Protector"]="protector",
	["Conqueror"]="conquistador",
	-- Translated by BakuraExel
	["Enable Showing item level / raid progression on tooltips"] = "Mostrar el nivel de objeto / Progreso en banda en la descripción emergente/tooltip",
	["Enable Showing Raid Progression Details on tooltips"] = "Mostrar progreso en banda detallado en la descripción emergente/tooltip",
	["Raid Progression Details"] = "Progreso en banda detallado",
	["Raid Progression"] = "Progreso en banda",
	["Enable Sending Enchantment Reminder"] = "Enviar recordatorio de encantamiento",
	["Enable Showing Gear Item Level on Character Frame"] = "Mostrar nivel de objeto promedio en el cuadro del personaje",
	["Average"] = "Promedio",
	["Scale"] = "Ampliar",
	["Average Item Level"] = "Nivel de objeto promedio",
	["Item Level"] = "Nivel de objeto",
	["Export"] = "Exportar",
	["Not enchanted"] = "No encantado",
	["Not socketed"] = "Sin gema",
	["Low level enchanted"] = "Encanto menor",
	["Low level socketed"] = "Gema menor",
	["Auto Scan"] = "Auto escáner",

} or GetLocale() == "itIT" and {
	["Set the amount of numbers past the decimal place to show"] = "Mostra il numero di cifre decimali da mostrare",
	["Show minimap button"]="Mostra il pulsante sulla minimappa",
	["Vanquisher"]="dominatore",
	["Protector"]="rotettore",
	["Conqueror"]="conquistatore",
	-- Translated by DocBerto65
	["Enable Showing item level / raid progression on tooltips"] = "Visualizza livello oggetto / progressione incursioni nei tooltip",
	["Enable Showing Raid Progression Details on tooltips"] = "Visualizza progresso incursioni dettagliato nei tooltip",
	["Raid Progression Details"] = "Progresso Incursioni Dettagliato",
	["Raid Progression"] = "Progressione incursioni",
	["Enable Sending Enchantment Reminder"] = "Abilita invio promemoria Incanto",
	["Enable Showing Gear Item Level on Character Frame"] = "Visualizza livello equipaggiamento sul frame personaggio",
	["Not enchanted"] = "Non incantato",
	["Not socketed"] = "Gemma mancante",
	["Low level enchanted"] = "Incantatatura di livello inferiore",
	["Low level socketed"] = "Gemma di livello inferiore",
	-- Translated by marcocio
	["Average"] = "Medio",
	["Scale"] = "Scala",
	["Average Item Level"] = "Livello oggetto medio",
	["Item Level"] = "Livello oggetto",
	["Export"] = "Esporta",
	["Auto Scan"] = "Scandisci automaticamente",

} or { }

setmetatable(MVP_L, {__index = function(self, key) rawset(self, key, key); return key; end})
